stages:
  - build
  - test
  - deploy
  - package
  - package-test

variables:
  BUILD_DIR: "build"
  PACKAGE_NAME: "matrix"
  PACKAGE_VERSION: "1.0.0"

.default_before_script: &default_before_script
  before_script:
    - apt-get update
    - apt-get install -y cmake g++ make dpkg rpm rpm-build rpmdevtools tar file

build-job:
  stage: build
  <<: *default_before_script
  script:
    - mkdir -p $BUILD_DIR
    - cd $BUILD_DIR
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build .
  artifacts:
    paths:
      - $BUILD_DIR
  tags:
    - ubuntu

test-job:
  stage: test
  <<: *default_before_script
  script:
    - cd $BUILD_DIR
    - ctest --verbose
  dependencies:
    - build-job
  artifacts:
    when: always
    reports:
      junit: build/Testing/Temporary/LastTest.log
  tags:
    - ubuntu

deploy-job:
  stage: deploy
  script:
    - mkdir -p /deploy
    - cp $BUILD_DIR/main_app /deploy/
  dependencies:
    - build-job
    - test-job
  artifacts:
    paths:
      - /deploy/main_app
  tags:
    - ubuntu

package-job:
  stage: package
  <<: *default_before_script
  script:
    - mkdir -p deb_build/DEBIAN
    - mkdir -p deb_build/usr/local/bin
    - cp $BUILD_DIR/main_app deb_build/usr/local/bin/

    - |
      cat <<EOF > deb_build/DEBIAN/control
      Package: $PACKAGE_NAME
      Version: $PACKAGE_VERSION
      Section: base
      Priority: optional
      Architecture: amd64
      Maintainer: Esternit <southonlyyt@gmail.com>
      Description: Matrix calculator app
      EOF

    - dpkg-deb --build deb_build packages/${PACKAGE_NAME}_${PACKAGE_VERSION}.deb

    - rpmdev-setuptree
    - mkdir -p ~/rpmbuild/SOURCES/${PACKAGE_NAME}
    - cp $BUILD_DIR/main_app ~/rpmbuild/SOURCES/${PACKAGE_NAME}/
    - tar -czf ~/rpmbuild/SOURCES/${PACKAGE_NAME}.tar.gz -C ~/rpmbuild/SOURCES ${PACKAGE_NAME}

    - |
      cat <<EOF > ~/rpmbuild/SPECS/${PACKAGE_NAME}.spec
      Name:           $PACKAGE_NAME
      Version:        $PACKAGE_VERSION
      Release:        1%{?dist}
      Summary:        Matrix calculator
      License:        MIT
      Source0:        ${PACKAGE_NAME}.tar.gz
      BuildArch:      x86_64

      %description
      Matrix calculator app.

      %prep
      %setup -q

      %build

      %install
      mkdir -p %{buildroot}/usr/local/bin
      cp -a main_app %{buildroot}/usr/local/bin/main_app

      %files
      /usr/local/bin/main_app

      %changelog
      * Tue Apr 29 2025 Esternit <southonlyyt@gmail.com> - ${PACKAGE_VERSION}-1
      - Initial build
      EOF

    - rpmbuild -ba ~/rpmbuild/SPECS/${PACKAGE_NAME}.spec
    - mkdir -p packages
    - cp ~/rpmbuild/RPMS/x86_64/*.rpm packages/

  dependencies:
    - build-job
    - deploy-job
  artifacts:
    paths:
      - packages/
  tags:
    - ubuntu

package-test-job:
  stage: package-test
  before_script:
    - apt-get update
    - apt-get install -y rpm
  script:
    - echo "Testing package installation..."
    - |
      if dpkg -i packages/*.deb; then
        echo "DEB installed"
      elif rpm -i packages/*.rpm; then
        echo "RPM installed"
      else
        echo "Installation failed" && exit 1
      fi
    - which main_app || echo "main_app not in PATH"
    - main_app || echo "main_app failed to run"
  dependencies:
    - package-job
  artifacts:
    when: always
  tags:
    - ubuntu
