stages:
  - build
  - test
  - deploy
  - package
  - package-test
variables:
  BUILD_DIR: "build"
build-job:
  stage: build
  before_script:
    - apt-get update && apt-get install -y cmake g++ make dpkg rpm
    - cd $CI_PROJECT_DIR
  script:
    - echo "Compiling the source code..."
    - mkdir -p $BUILD_DIR
    - cd $BUILD_DIR
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build .
    - echo "Compile complete."
  artifacts:
    paths:
      - $BUILD_DIR
  tags:
    - ubuntu
test-job:
  stage: test
  script:
    - echo "Running tests..."
    - cd $BUILD_DIR
    - ctest --verbose
  dependencies:
    - build-job
  artifacts:
    when: always
    reports:
      junit: build/Testing/Temporary/LastTest.log
  tags:
    - ubuntu
deploy-job:
  stage: deploy
  script:
    - echo "Deploying artifacts..."
    - mkdir -p /deploy
    - cp -r $BUILD_DIR/main_app /deploy/
  dependencies:
    - build-job
    - test-job
  artifacts:
    paths:
      - /deploy/main_app
  tags:
    - ubuntu
package-job:
  stage: package
  script:
    - echo "Installing for packaging..."
    - cd $BUILD_DIR
    - apt update && apt install -y file rpm cpio fakeroot
    - make install DESTDIR=install_dir

    - echo "Running CPack with debug output..."
    - mkdir -p packages
    - cpack -B packages
  dependencies:
    - build-job
    - deploy-job
  artifacts:
    paths:
      - packages/
  tags:
    - ubuntu
package-test-job:
  stage: package-test
  before_script:
    - apt-get update && apt install -y rpm
  script:
    - echo "Testing package installation..."
    - sudo dpkg -i build/packages/*.deb || sudo rpm -i build/packages/*.rpm
    - which main_app
    - main_app
  dependencies:
    - build-job
    - package-job
  artifacts:
    when: always
  tags:
    - ubuntu
