stages:
  - build
  - test

build-job:
  stage: build
before_script:
  - apt-get update && apt-get install -y cmake g++ make libgtest-dev
  - cd /usr/src/gtest && cmake . && make && cp *.a /usr/lib
script:
    - echo "Compiling the code..."
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build . --config Debug
    - echo "Compile complete."
  artifacts:
    paths:
      - build/
  tags:
    - ubuntu

test-job:
  stage: test
  script:
    - echo "Running tests..."
    - cd build
    - ./Debug/test_runner
  dependencies:
    - build-job
  tags:
    - ubuntu
