stages:
  - build
  - test

build-job:
  stage: build
  before_script:
    - apt-get update && apt-get install -y cmake g++ make libgtest-dev
    - cd /usr/src/gtest
    - cmake .
    - make
    - cp libgtest.a libgtest_main.a /usr/lib
    - cd $CI_PROJECT_DIR # ✅ Возвращаемся в проект перед сборкой

  script:
    - echo "Compiling the code..."
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - cmake --build .
    - echo "Compile complete."

  artifacts:
    paths:
      - build/
  tags:
    - ubuntu

test-job:
  stage: test
  script:
    - echo "Running tests..."
    - cd build
    - ./test_runner
  dependencies:
    - build-job
  tags:
    - ubuntu
