stages:
  - build
  - test
  - deploy
  - package
  - package-test

variables:
  BUILD_DIR: "build"
  INSTALL_DIR: "$CI_PROJECT_DIR/install_dir"

build-job:
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y cmake g++ make dpkg rpm rpm2cpio fakeroot tar file
  script:
    - echo "Compiling the source code..."
    - mkdir -p $BUILD_DIR
    - cd $BUILD_DIR
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build .
    - echo "Compile complete."
  artifacts:
    paths:
      - $BUILD_DIR
  tags:
    - ubuntu

test-job:
  stage: test
  script:
    - echo "Running tests..."
    - cd $BUILD_DIR
    - ctest --verbose
  dependencies:
    - build-job
  artifacts:
    when: always
    reports:
      junit: build/Testing/Temporary/LastTest.log
  tags:
    - ubuntu

deploy-job:
  stage: deploy
  script:
    - echo "Deploying artifacts..."
    - mkdir -p /deploy
    - cp -r $BUILD_DIR/main_app /deploy/
  dependencies:
    - build-job
    - test-job
  artifacts:
    paths:
      - /deploy/main_app
  tags:
    - ubuntu

package-job:
  stage: package
  before_script:
    - apt-get update
    - apt-get install -y fakeroot rpm rpm2cpio dpkg-dev tar file
  script:
    - echo "Preparing manual installation directory..."
    - cd $BUILD_DIR
    - make install DESTDIR=$INSTALL_DIR

    - echo "Building DEB..."
    - mkdir -p deb_package/DEBIAN
    - |
      cat > deb_package/DEBIAN/control <<EOF
      Package: matrix-calculator
      Version: 1.0.0
      Section: base
      Priority: optional
      Architecture: amd64
      Maintainer: Esternit <southonlyyt@gmail.com>
      Description: A simple matrix calculator written in C++
      Depends: libc6 (>= 2.27)
      EOF
    - cp -r $INSTALL_DIR/* deb_package/
    - dpkg-deb --build deb_package ../matrix-calculator.deb

    - echo "Building RPM..."
    - mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    - mkdir -p rpmbuildroot/usr/bin
    - cp $INSTALL_DIR/usr/bin/main_app rpmbuildroot/usr/bin/
    - |
      cat > ~/rpmbuild/SPECS/matrix-calculator.spec <<EOF
      Name: matrix-calculator
      Version: 1.0.0
      Release: 1
      Summary: A simple matrix calculator
      License: MIT
      Group: Development/Tools
      BuildRoot: %{_tmppath}/%{name}-%{version}-build
      Prefix: /usr

      %description
      A simple matrix calculator written in C++.

      %files
      /usr/bin/main_app

      %prep
      %build
      %install
        mkdir -p \$RPM_BUILD_ROOT/usr/bin
        cp rpmbuildroot/usr/bin/main_app \$RPM_BUILD_ROOT/usr/bin/

      %clean
        rm -rf \$RPM_BUILD_ROOT
      EOF

    - rpmbuild -bb ~/rpmbuild/SPECS/matrix-calculator.spec
    - mkdir -p packages
    - mv ../matrix-calculator.deb packages/
    - find ~/rpmbuild/RPMS -name "*.rpm" -exec cp {} packages/ \;
  dependencies:
    - build-job
  artifacts:
    paths:
      - packages/
  tags:
    - ubuntu

package-test-job:
  stage: package-test
  before_script:
    - apt-get update
    - apt-get install -y rpm
  script:
    - echo "Testing package installation..."
    - sudo dpkg -i packages/*.deb || true
    - sudo rpm -i --force --nodeps packages/*.rpm || true
    - which main_app || echo "main_app not found in PATH"
    - main_app || echo "main_app execution failed"
  dependencies:
    - package-job
  artifacts:
    when: always
  tags:
    - ubuntu
